# Generated by Django 5.2.13 on 2026-04-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Aksiya'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='promotion_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Aksiya narxi'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='promotion_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aksiya nomi'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Aksiya sarlavhasi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Rasm')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='Chegirma %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
