# Generated by Django 5.2.13 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_menuitem_is_promotion_menuitem_promotion_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='Chegirma %'),
        ),
    ]
