# Generated by Django 5.2.13 on 2026-04-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_add_chat_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bron vaqti'),
        ),
    ]
