# Generated by Django 5.2.13 on 2026-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_order_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='Admin javobi'),
        ),
    ]
