# Generated by Django 5.2.13 on 2026-04-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_review_admin_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tushum')),
                ('expenses', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Xarajat')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Foyda')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Buyurtmalar soni')),
                ('avg_order_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="O'rtacha buyurtma")),
                ('customers_count', models.IntegerField(default=0, verbose_name='Mijozlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Kunlik hisobot',
                'verbose_name_plural': 'Kunlik hisobotlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('boss', 'Boshqaruvchi'), ('chef', 'oshpaz'), ('waiter', 'ofitsiant'), ('cashier', 'kassir'), ('courier', 'yetkazuvchi'), ('cleaner', 'tozalovchi')], max_length=20, verbose_name='Lavozim')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Ish haqi')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Soatlik stavka')),
                ('hire_date', models.DateField(verbose_name='Ishga qabul sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('on_leave', "Ta'til"), ('fired', 'Ishdan ketgan')], default='active', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ishlagan soat')),
                ('status', models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikgan'), ('day_off', "Ta'til")], default='present', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='restaurants.employee')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish vaqti')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('guest_count', models.IntegerField(default=1, verbose_name='Mehmonlar soni')),
                ('order_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Buyurtma summasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holati')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurants.table')),
            ],
            options={
                'verbose_name': 'Stol sessiyasi',
                'verbose_name_plural': 'Stol sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('category', models.CharField(choices=[('food', 'Oziq-ovqat'), ('drink', 'Ichimliklar'), ('packaging', 'Qadoqlash'), ('cleaning', 'Tozalash'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya')),
                ('unit', models.CharField(max_length=20, verbose_name='Birlik (kg, dona, l...)')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Miqdori')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimal miqdori')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Narxi')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Yetkazuvchi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Ombor elementi',
                'verbose_name_plural': 'Ombor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('adjust', 'Korreksiya')], max_length=10, verbose_name='Turi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Narxi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.CharField(max_length=100, verbose_name="Kim qo'shdi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='restaurants.warehouseitem')),
            ],
            options={
                'verbose_name': 'Ombor yozuvi',
                'verbose_name_plural': 'Ombor yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
