# Generated by Django 5.2.13 on 2026-04-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_dailyreport_employee_attendance_tablesession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, verbose_name="Buyurtmalar ro'yxati")),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Yuborilgan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guruh buyurtmasi',
                'verbose_name_plural': 'Guruh buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_user_id', models.IntegerField(verbose_name="To'lovchi ID")),
                ('payer_name', models.CharField(max_length=100, verbose_name="To'lovchi ismi")),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Summa')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme')], max_length=20, verbose_name="To'lov usuli")),
                ('is_settled', models.BooleanField(default=False, verbose_name='Hisob-kitob qilingan')),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.grouporder')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QaniKetedikEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_user_id', models.IntegerField(verbose_name='Tashkilotchi ID')),
                ('host_name', models.CharField(max_length=100, verbose_name='Tashkilotchi ismi')),
                ('host_phone', models.CharField(max_length=20, verbose_name='Tashkilotchi telefon')),
                ('title', models.CharField(max_length=200, verbose_name='Tadbir nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('event_date', models.DateField(verbose_name='Tadbir sanasi')),
                ('event_time', models.TimeField(verbose_name='Tadbir vaqti')),
                ('status', models.CharField(choices=[('draft', 'Qoralamada'), ('active', 'Faol'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20)),
                ('max_guests', models.IntegerField(default=10, verbose_name='Maksimal mehmonlar')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Check-in qilingan')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='restaurants.table')),
            ],
            options={
                'verbose_name': 'Qani Ketdik tadbiri',
                'verbose_name_plural': 'Qani Ketdik tadbirlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grouporder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='restaurants.qaniketedikevent'),
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user_id', models.IntegerField(blank=True, null=True)),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Mehmon telefoni')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Mehmon ismi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('declined', 'Rad etildi'), ('arrived', 'Keldi')], default='pending', max_length=20)),
                ('can_order_food', models.BooleanField(default=False, verbose_name='Taom tanlash huquqi')),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='restaurants.qaniketedikevent')),
            ],
            options={
                'verbose_name': 'Taklifnoma',
                'verbose_name_plural': 'Taklifnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
