# Generated by Django 5.2.13 on 2026-04-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_grouporder_eventpayment_qaniketedikevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='restaurants.qaniketedikevent'),
        ),
    ]
