# Generated by Django 5.2.13 on 2026-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Olib ketish'), ('delivery', 'Yetkazib berish')], default='pickup', max_length=20, verbose_name='Yetkazish turi'),
        ),
    ]
