# Generated by Django 5.2.13 on 2026-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantadmin',
            name='can_add_promotion',
            field=models.BooleanField(default=False, verbose_name="Aksiya qo'shish ruxsat"),
        ),
    ]
