# Generated by Django 5.2.13 on 2026-04-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_restaurantadmin_can_add_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_bookings',
            field=models.BooleanField(default=False, verbose_name='Bronlarni boshqarish'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_manage_orders',
            field=models.BooleanField(default=False, verbose_name='Buyurtmalarni boshqarish'),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Login'),
        ),
    ]
