# Generated by Django 5.2.13 on 2026-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_staff_can_manage_bookings_staff_can_manage_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_warehouse',
            field=models.BooleanField(default=False, verbose_name='Omborni boshqarish'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('manager', 'Menejer'), ('cook', 'Oshpaz'), ('warehouse', 'Omborxonachi')], max_length=50, verbose_name='Lavozim'),
        ),
    ]
